const NodeFilter = {
  FILTER_ACCEPT: 100,
  FILTER_REJECT: 101,
  FILTER_SKIP: 102,
  SHOW_ALL: -1,
  SHOW_COMMENT: 128,
  SHOW_DOCUMENT: 256,
  SHOW_DOCUMENT_FRAGMENT: 1024,
  SHOW_DOCUMENT_TYPE: 512,
  SHOW_ELEMENT: 1,
  SHOW_PROCESSING_INSTRUCTION: 64,
  SHOW_TEXT: 4
};

module.exports = NodeFilter;
