import createSymbol from './create-symbol';
export const connected = createSymbol();
export const created = createSymbol();
export const name = '____skate_name';
export const props = createSymbol();
export const ref = createSymbol();
export const renderer = createSymbol();
export const rendering = createSymbol();
export const rendererDebounced = createSymbol();
export const shadowRoot = createSymbol();
export const updated = createSymbol();
