export const created = '____created';
export const events = '____events';
export const name = '____name';
export const props = '____props';
export const renderer = '____renderer';
export const rendererDebounced = '____rendererDebounced';
export const shadowRoot = '____shadowRoot';
export const v0ShadowDOMProperty = 'createShadowRoot'; // property used to check for shadowDOMv0 support
export const v1ShadowDOMProperty = 'attachShadow'; // property used to check for shadowDOMv1 support
